FROM nginx:latest


COPY . /usr/share/nginx/html/
RUN find /usr/share/nginx/html/ -type f -exec sed -i 's|https://eucan.ddns.net|http://eucan.ddns.net|g' {} +

# Remove the default nginx.conf
RUN rm /etc/nginx/conf.d/default.conf

# # Replace with our own nginx.conf
COPY nginx.conf /etc/nginx/conf.d/
