resolver 127.0.0.11 valid=10s ipv6=off;

acme_issuer acme {
  uri         https://acme-staging-v02.api.letsencrypt.org/directory;
  challenge   http-01;
  state_path  /var/cache/nginx/acme-example;
  accept_terms_of_service;
}

acme_shared_zone zone=ngx_acme_shared:1M;

server {
  listen 443 ssl;
  server_name eucan.ddns.net;

  http2 on;
  http3 on; # Enable HTTP/3
  client_max_body_size 2G;

  acme_certificate acme;

  ssl_certificate       $acme_certificate;
  ssl_certificate_key   $acme_certificate_key;
  ssl_certificate_cache max=2;
  error_page 301 /custom_301.html;

  server_tokens off;
  more_clear_headers Server;
  location / {
    proxy_pass http://frontend:8000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_pass_request_headers on;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

}

server {
  listen 3000 ssl;

  http2 on;
  http3 on; # Enable HTTP/3
  client_max_body_size 2G;
  server_name eucan.ddns.net;
  error_page 301 /custom_301.html;

  acme_certificate acme;

  ssl_certificate       $acme_certificate;
  ssl_certificate_key   $acme_certificate_key;
  ssl_certificate_cache max=2;

  server_tokens off;
  more_clear_headers Server;
  location / {
    proxy_pass http://backend:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass_request_headers on;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

}

server {
  listen 80;
  listen 8000;

  server_name _;

  server_tokens off;
  more_clear_headers Server;

  location = /custom_301.html {
    root /usr/share/nginx/html;
    internal; # Prevents direct external access to this file
  }

	location /.well-known/acme-challenge/ {
    root /var/www/html;
  }
	location /{
    return 301 https://$host$request_uri;
	}

}
